window.UTBK_QUESTIONS = [
  {
    "id": "S-140",
    "no_misi_default": 2,
    "tema": "PU",
    "sub_tema": "Penalaran Induktif",
    "level_kesulitan": 2,
    "materi_pengantar": "Penalaran induktif: dari fakta-fakta khusus → kesimpulan umum. Soal tipe: 'paling mungkin benar', 'mendukung/melemahkan argumen'. Tips: cari pernyataan yang langsung didukung teks, hindari asumsi berlebih.",
    "pertanyaan": "Perhatikan teks berikut! Sebuah penelitian dari Harvard Medical School menemukan bahwa tidur cukup (7–9 jam per malam) dapat meningkatkan kemampuan konsentrasi dan produktivitas. Penelitian tersebut melibatkan 500 mahasiswa selama satu semester. Mahasiswa yang tidur kurang dari 6 jam menunjukkan penurunan nilai rata-rata sebesar 15% dibandingkan kelompok yang tidur cukup.\n\nPernyataan yang PALING MUNGKIN BENAR berdasarkan teks tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Semua mahasiswa yang tidur cukup pasti mendapat nilai sempurna.",
    "opsi_b": "Mahasiswa yang tidur kurang dari 6 jam kemungkinan besar memiliki performa akademik yang lebih rendah.",
    "opsi_c": "Tidur lebih dari 9 jam terbukti meningkatkan nilai akademik secara signifikan.",
    "opsi_d": "Penelitian Harvard melibatkan seluruh mahasiswa di dunia.",
    "opsi_e": "Kurang tidur tidak berpengaruh pada produktivitas jika mahasiswa belajar keras.",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Teks menyebutkan bahwa mahasiswa yang tidur kurang dari 6 jam mengalami penurunan nilai sebesar 15%. Pernyataan B paling sesuai dengan fakta dalam teks karena didukung data langsung. Pernyataan lain mengandung asumsi berlebih yang tidak disebutkan dalam teks.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-141",
    "no_misi_default": 3,
    "tema": "PU",
    "sub_tema": "Penalaran Deduktif",
    "level_kesulitan": 3,
    "materi_pengantar": "Silogisme: tarik kesimpulan dari dua premis. Premis 1 (umum) + Premis 2 (khusus) → Kesimpulan. Pastikan subjek, predikat, dan term tengah digunakan dengan benar.",
    "pertanyaan": "Perhatikan pernyataan berikut!\n• Semua kendaraan bermotor memerlukan bahan bakar untuk beroperasi.\n• Mobil listrik adalah kendaraan bermotor.\n• Beberapa kendaraan bermotor menggunakan bahan bakar fosil.\n\nSimpulan yang TEPAT berdasarkan pernyataan-pernyataan tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Semua mobil listrik menggunakan bahan bakar fosil.",
    "opsi_b": "Semua kendaraan bermotor yang menggunakan bahan bakar fosil adalah mobil.",
    "opsi_c": "Mobil listrik memerlukan bahan bakar untuk beroperasi.",
    "opsi_d": "Bahan bakar fosil adalah satu-satunya jenis bahan bakar kendaraan bermotor.",
    "opsi_e": "Beberapa mobil listrik tidak memerlukan bahan bakar.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Menggunakan silogisme: Premis 1: Semua kendaraan bermotor memerlukan bahan bakar. Premis 2: Mobil listrik adalah kendaraan bermotor. Kesimpulan: Mobil listrik memerlukan bahan bakar untuk beroperasi. Premis ketiga tidak berkaitan langsung dengan mobil listrik.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-142",
    "no_misi_default": 4,
    "tema": "PU",
    "sub_tema": "Penalaran Induktif",
    "level_kesulitan": 3,
    "materi_pengantar": "Soal memperkuat argumen: cari pernyataan yang langsung mendukung klaim utama dengan bukti konkret. Soal memperlemah: cari pernyataan yang menunjukkan klaim tidak valid.",
    "pertanyaan": "Perhatikan teks berikut! Kepala Dinas Pertanian menyatakan bahwa penerapan sistem irigasi tetes dapat meningkatkan hasil panen petani di daerah kering karena air dialirkan langsung ke akar tanaman sehingga tidak terjadi pemborosan air.\n\nPernyataan berikut yang MEMPERKUAT argumen Kepala Dinas Pertanian tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Petani di daerah basah tidak membutuhkan sistem irigasi tetes.",
    "opsi_b": "Beberapa negara di Eropa menggunakan sistem irigasi tetes untuk lahan pertanian mereka.",
    "opsi_c": "Data menunjukkan daerah yang menggunakan irigasi tetes mengalami peningkatan hasil panen hingga 40% dengan penggunaan air 50% lebih sedikit.",
    "opsi_d": "Sistem irigasi konvensional lebih mudah diterapkan daripada irigasi tetes.",
    "opsi_e": "Tidak semua jenis tanaman cocok dengan sistem irigasi tetes.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Pernyataan C langsung mendukung klaim dengan data konkret: peningkatan hasil panen 40% dan efisiensi air 50%. Pernyataan A dan D tidak relevan, B terlalu umum, sedangkan E justru memperlemah argumen.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-143",
    "no_misi_default": 5,
    "tema": "PU",
    "sub_tema": "Penalaran Deduktif",
    "level_kesulitan": 4,
    "materi_pengantar": "Modus Tollens: Jika P→Q dan ¬Q, maka ¬P. Silogisme berantai: jika P→Q dan Q→R, maka P→R. Keduanya dapat dikombinasikan.",
    "pertanyaan": "Perhatikan pernyataan berikut!\n• Jika seseorang rajin belajar, maka ia akan lulus ujian.\n• Jika seseorang lulus ujian, maka ia akan mendapat beasiswa.\n• Budi tidak mendapat beasiswa.\n\nSimpulan yang PALING TEPAT dari pernyataan-pernyataan tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Budi rajin belajar tetapi tidak lulus ujian.",
    "opsi_b": "Budi pasti tidak lulus ujian.",
    "opsi_c": "Budi tidak rajin belajar.",
    "opsi_d": "Budi mendapat beasiswa dengan cara lain.",
    "opsi_e": "Budi tidak lulus ujian karena tidak rajin belajar.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Dengan silogisme berantai: rajin belajar → lulus ujian → mendapat beasiswa. Karena Budi tidak mendapat beasiswa (¬R), maka dengan Modus Tollens: Budi tidak lulus ujian (¬Q), dan lebih lanjut: Budi tidak rajin belajar (¬P). Simpulan paling tepat adalah C.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-144",
    "no_misi_default": 6,
    "tema": "PU",
    "sub_tema": "Penalaran Kuantitatif",
    "level_kesulitan": 5,
    "materi_pengantar": "Membaca tabel: 1) Perhatikan judul dan satuan, 2) Identifikasi nilai yang ditanyakan, 3) Hitung selisih, persentase, atau perbandingan sesuai soal.",
    "pertanyaan": "Perhatikan tabel penjualan (dalam unit) berikut!\n\nKuartal | Produk A | Produk B | Produk C\nQ1      |   120    |    85    |    95\nQ2      |   135    |    90    |   110\nQ3      |   150    |   105    |   125\nQ4      |   165    |   120    |   140\n\nBerdasarkan tabel tersebut, pernyataan yang BENAR adalah ...",
    "ada_latex": false,
    "opsi_a": "Total penjualan Produk B lebih besar dari total penjualan Produk C sepanjang tahun.",
    "opsi_b": "Produk A mengalami kenaikan penjualan yang sama setiap kuartal.",
    "opsi_c": "Selisih penjualan Produk A dan Produk C pada Q4 adalah 30 unit.",
    "opsi_d": "Total penjualan ketiga produk pada Q2 adalah 300 unit.",
    "opsi_e": "Produk C mengalami kenaikan penjualan tertinggi dari Q3 ke Q4.",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Produk A: Q1=120, Q2=135 (+15), Q3=150 (+15), Q4=165 (+15). Kenaikannya konsisten 15 unit setiap kuartal. Opsi A salah (total B=400, C=470). Opsi C salah (165-140=25). Opsi D salah (135+90+110=335). Opsi E salah (semua naik 15).",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-145",
    "no_misi_default": 1,
    "tema": "PPU",
    "sub_tema": "Ide Pokok",
    "level_kesulitan": 1,
    "materi_pengantar": "Ide pokok adalah inti paragraf. Cari kalimat utama: di awal (deduktif), di akhir (induktif), atau di awal dan akhir (campuran). Kalimat utama bersifat umum, kalimat penjelas bersifat khusus.",
    "pertanyaan": "Bacalah paragraf berikut! Plastik merupakan salah satu bahan yang paling banyak digunakan dalam kehidupan sehari-hari. Mulai dari kemasan makanan, botol minum, tas belanja, hingga perabot rumah tangga, hampir semuanya terbuat dari plastik. Namun, penggunaan plastik yang berlebihan telah menimbulkan masalah lingkungan yang serius. Sampah plastik yang tidak terurai mencemari lautan, tanah, dan bahkan masuk ke rantai makanan manusia melalui mikroplastik.\n\nIde pokok paragraf tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Plastik digunakan dalam berbagai produk sehari-hari.",
    "opsi_b": "Plastik merupakan bahan yang paling banyak digunakan namun menimbulkan masalah lingkungan.",
    "opsi_c": "Sampah plastik mencemari lautan dan tanah.",
    "opsi_d": "Mikroplastik masuk ke dalam rantai makanan manusia.",
    "opsi_e": "Penggunaan plastik harus segera dihentikan.",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Paragraf ini bersifat campuran: kalimat pertama (umum) dan kalimat ketiga-keempat memperkuat gagasan tentang dampak negatif. Ide pokok mencakup dua sisi: plastik banyak digunakan (positif) sekaligus menimbulkan masalah lingkungan (negatif). Opsi B paling komprehensif.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-146",
    "no_misi_default": 2,
    "tema": "PPU",
    "sub_tema": "Penggunaan Ejaan",
    "level_kesulitan": 2,
    "materi_pengantar": "EYD: Huruf kapital untuk awal kalimat, nama diri, nama jabatan yang mendahului nama, dan nama peristiwa bersejarah. Kata asing yang sudah dibakukan tidak perlu dicetak miring. Istilah asing yang belum dibakukan dicetak miring.",
    "pertanyaan": "Penulisan kalimat yang sesuai dengan kaidah EYD yang benar adalah ...",
    "ada_latex": false,
    "opsi_a": "Presiden Jokowi menyampaikan pidato di hari kemerdekaan.",
    "opsi_b": "presiden jokowi menyampaikan Pidato di Hari Kemerdekaan.",
    "opsi_c": "Presiden Jokowi menyampaikan pidato di Hari Kemerdekaan.",
    "opsi_d": "Presiden jokowi Menyampaikan pidato di hari kemerdekaan.",
    "opsi_e": "presiden Jokowi menyampaikan pidato di hari kemerdekaan.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "'Presiden' ditulis kapital karena mendahului nama diri. 'Jokowi' adalah nama diri, ditulis kapital. 'Hari Kemerdekaan' ditulis kapital karena merupakan nama peristiwa bersejarah. 'pidato' bukan nama diri sehingga huruf kecil.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-147",
    "no_misi_default": 3,
    "tema": "PPU",
    "sub_tema": "Pengetahuan IPA",
    "level_kesulitan": 3,
    "materi_pengantar": "Fotosintesis: proses pembuatan makanan oleh tumbuhan menggunakan cahaya matahari. Persamaan: CO₂ + H₂O + cahaya → glukosa (C₆H₁₂O₆) + O₂. Terjadi di kloroplas yang mengandung klorofil.",
    "pertanyaan": "Proses fotosintesis pada tumbuhan menghasilkan ...",
    "ada_latex": false,
    "opsi_a": "Karbon dioksida dan air",
    "opsi_b": "Oksigen dan glukosa",
    "opsi_c": "Nitrogen dan glukosa",
    "opsi_d": "Oksigen dan karbon dioksida",
    "opsi_e": "Glukosa dan nitrogen",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Reaksi fotosintesis: 6CO₂ + 6H₂O + cahaya → C₆H₁₂O₆ (glukosa) + 6O₂. Tumbuhan menyerap CO₂ dan H₂O lalu menghasilkan glukosa sebagai sumber energi dan O₂ (oksigen) yang dilepaskan ke udara.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-148",
    "no_misi_default": 4,
    "tema": "PPU",
    "sub_tema": "Pemahaman Teks",
    "level_kesulitan": 3,
    "materi_pengantar": "Simpulan mencakup keseluruhan isi teks, bukan hanya satu bagian. Hindari simpulan yang terlalu sempit, terlalu luas, atau mengandung informasi di luar teks.",
    "pertanyaan": "Bacalah teks berikut! Revolusi Industri 4.0 membawa perubahan besar dalam dunia ketenagakerjaan. Otomatisasi dan kecerdasan buatan (AI) diperkirakan akan menggantikan sekitar 85 juta pekerjaan pada 2025. Namun, perkembangan teknologi ini juga diprediksi akan menciptakan 97 juta pekerjaan baru yang membutuhkan keahlian di bidang teknologi, data, dan kreativitas. Para ahli menyarankan agar generasi muda mempersiapkan diri dengan menguasai keterampilan digital dan kemampuan berpikir kritis.\n\nSimpulan yang paling tepat dari teks tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Revolusi Industri 4.0 hanya merugikan para pekerja karena mengurangi lapangan kerja.",
    "opsi_b": "Kecerdasan buatan akan menggantikan seluruh pekerjaan manusia pada tahun 2025.",
    "opsi_c": "Revolusi Industri 4.0 mengubah lanskap ketenagakerjaan dengan menghapus pekerjaan lama sekaligus menciptakan peluang baru yang membutuhkan keahlian digital.",
    "opsi_d": "Generasi muda tidak perlu khawatir dengan Revolusi Industri 4.0.",
    "opsi_e": "Keterampilan digital adalah satu-satunya cara untuk bertahan di era Revolusi Industri 4.0.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Simpulan harus mencerminkan keseluruhan isi teks. Teks membahas dua sisi: pekerjaan yang tergantikan (85 juta) dan pekerjaan baru yang tercipta (97 juta). Pernyataan C mencakup keduanya tanpa berlebihan.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-149",
    "no_misi_default": 5,
    "tema": "PPU",
    "sub_tema": "Pengetahuan IPA",
    "level_kesulitan": 4,
    "materi_pengantar": "IPS – Globalisasi: proses integrasi antarnegara di bidang ekonomi, budaya, dan teknologi. Dampak positif: akses pasar luas, transfer teknologi. Dampak negatif: dominasi asing, homogenisasi budaya.",
    "pertanyaan": "Salah satu dampak positif dari globalisasi dalam bidang ekonomi adalah ...",
    "ada_latex": false,
    "opsi_a": "Meningkatnya pengangguran akibat masuknya tenaga kerja asing secara massal.",
    "opsi_b": "Hilangnya produk-produk lokal dari pasaran karena kalah bersaing.",
    "opsi_c": "Terbukanya akses pasar internasional bagi produk dalam negeri.",
    "opsi_d": "Meningkatnya ketergantungan mutlak terhadap negara maju.",
    "opsi_e": "Berkurangnya persaingan usaha sehingga harga produk menjadi lebih stabil.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Globalisasi membuka pasar internasional sehingga produk dalam negeri dapat dijual ke luar negeri (ekspor meningkat). Ini merupakan dampak positif yang nyata. Opsi lain menggambarkan dampak negatif atau pernyataan yang tidak akurat.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-150",
    "no_misi_default": 1,
    "tema": "PBM",
    "sub_tema": "Ide Pokok",
    "level_kesulitan": 1,
    "materi_pengantar": "Ide pokok paragraf deduktif berada di awal kalimat (pernyataan umum). Kalimat-kalimat berikutnya adalah penjelas. Ciri: kalimat pertama bersifat luas/umum.",
    "pertanyaan": "Bacalah paragraf berikut! Indonesia memiliki kekayaan alam yang luar biasa. Hutan tropis yang membentang dari Sumatera hingga Papua menjadi rumah bagi ribuan spesies flora dan fauna yang tidak ditemukan di tempat lain. Lautan Indonesia yang luas menyimpan berbagai jenis ikan, terumbu karang, dan biota laut yang menjadi sumber penghidupan jutaan nelayan. Keragaman hayati ini menjadikan Indonesia salah satu negara dengan megabiodiversitas tertinggi di dunia.\n\nIde pokok paragraf tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Hutan tropis Indonesia membentang dari Sumatera hingga Papua.",
    "opsi_b": "Lautan Indonesia kaya akan ikan dan terumbu karang.",
    "opsi_c": "Kekayaan alam Indonesia menjadi sumber penghidupan jutaan nelayan.",
    "opsi_d": "Indonesia memiliki kekayaan alam yang luar biasa.",
    "opsi_e": "Indonesia adalah negara dengan megabiodiversitas tertinggi di dunia.",
    "kunci_jawaban": "D",
    "penjelasan_jawaban": "Paragraf ini bersifat deduktif. Kalimat pertama 'Indonesia memiliki kekayaan alam yang luar biasa' adalah kalimat utama (umum). Kalimat-kalimat berikutnya (hutan, lautan, megabiodiversitas) adalah kalimat penjelas yang bersifat khusus.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-151",
    "no_misi_default": 2,
    "tema": "PBM",
    "sub_tema": "Simpulan Tersirat",
    "level_kesulitan": 2,
    "materi_pengantar": "Simpulan yang tepat mencakup keseluruhan isi teks secara seimbang. Hindari simpulan yang terlalu memihak satu sisi jika teks menyajikan dua sudut pandang.",
    "pertanyaan": "Bacalah teks berikut! (1) Sampah elektronik atau e-waste merupakan salah satu tantangan lingkungan terbesar abad ini. (2) Setiap tahun, lebih dari 50 juta ton perangkat elektronik dibuang di seluruh dunia. (3) Sebagian besar sampah ini berakhir di negara-negara berkembang yang minim fasilitas daur ulang. (4) Kandungan berbahaya dalam e-waste seperti timbal, merkuri, dan kadmium dapat mencemari tanah dan air tanah. (5) Namun, di sisi lain, e-waste juga mengandung material berharga seperti emas, perak, dan tembaga yang dapat didaur ulang.\n\nSimpulan yang paling tepat dari teks tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "E-waste harus segera dilarang produksinya di seluruh dunia.",
    "opsi_b": "E-waste merupakan masalah lingkungan yang kompleks namun juga menyimpan potensi ekonomi dari material daur ulang.",
    "opsi_c": "Negara berkembang adalah satu-satunya pihak yang bertanggung jawab atas masalah e-waste.",
    "opsi_d": "Material berharga dalam e-waste dapat menggantikan kebutuhan penambangan mineral baru.",
    "opsi_e": "Kandungan berbahaya e-waste hanya berdampak pada negara-negara berkembang saja.",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Teks menyajikan dua sisi e-waste: dampak negatif (pencemaran lingkungan) dan potensi positif (material daur ulang berharga). Simpulan B paling seimbang dan komprehensif. Opsi lain bersifat terlalu ekstrem atau tidak sesuai teks.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-152",
    "no_misi_default": 3,
    "tema": "PBM",
    "sub_tema": "Menentukan Judul",
    "level_kesulitan": 2,
    "materi_pengantar": "Judul yang tepat: (1) mencakup seluruh isi teks, (2) tidak terlalu sempit atau luas, (3) menarik dan informatif, (4) menggunakan huruf kapital di awal tiap kata kecuali konjungsi.",
    "pertanyaan": "Bacalah teks berikut! Minat baca masyarakat Indonesia masih tergolong rendah dibandingkan negara-negara di Asia Tenggara. Berdasarkan survei UNESCO, Indonesia berada di peringkat kedua terbawah dalam hal minat baca dari 61 negara yang disurvei. Rata-rata orang Indonesia hanya membaca 0,001 buku per tahun. Padahal, membaca merupakan fondasi penting dalam membangun sumber daya manusia yang berkualitas. Oleh karena itu, berbagai pihak mulai dari pemerintah, sekolah, hingga keluarga perlu berkolaborasi untuk menumbuhkan budaya baca sejak dini.\n\nJudul yang paling tepat untuk teks tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Rendahnya Minat Baca Masyarakat Indonesia dan Upaya Mengatasinya",
    "opsi_b": "Indonesia Negara Paling Rendah Minat Bacanya di Dunia",
    "opsi_c": "Pentingnya Membaca Bagi Pembangunan Sumber Daya Manusia",
    "opsi_d": "Survei UNESCO tentang Minat Baca Global",
    "opsi_e": "Budaya Baca yang Mulai Ditingkatkan Pemerintah Indonesia",
    "kunci_jawaban": "A",
    "penjelasan_jawaban": "Teks membahas dua hal: (1) rendahnya minat baca Indonesia berdasarkan data UNESCO, dan (2) upaya mengatasinya melalui kolaborasi berbagai pihak. Judul A mencakup keduanya. Opsi lain hanya mencakup satu bagian teks saja.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-153",
    "no_misi_default": 4,
    "tema": "PBM",
    "sub_tema": "Melengkapi Teks",
    "level_kesulitan": 3,
    "materi_pengantar": "Kalimat pengisi teks rumpang harus: (1) koheren dengan kalimat sebelum dan sesudahnya, (2) tidak mengulang informasi yang sudah ada, (3) menjadi jembatan logis antara dua bagian teks.",
    "pertanyaan": "Bacalah teks berikut! Perubahan iklim merupakan ancaman nyata yang semakin dirasakan oleh seluruh penduduk bumi. Suhu rata-rata global terus meningkat akibat emisi gas rumah kaca dari aktivitas manusia. [...] Kondisi ini menyebabkan mencairnya es di kutub, naiknya permukaan air laut, dan perubahan pola curah hujan yang ekstrem. Para ilmuwan memperingatkan bahwa jika tidak ada tindakan nyata, dampaknya akan semakin parah pada pertengahan abad ini.\n\nKalimat yang paling tepat untuk mengisi bagian rumpang [...] dalam teks tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Cuaca di Indonesia sangat tidak menentu belakangan ini.",
    "opsi_b": "Industri pertanian menjadi sektor yang paling terdampak oleh perubahan iklim.",
    "opsi_c": "Pembakaran bahan bakar fosil, deforestasi, dan aktivitas industri menjadi penyumbang terbesar emisi tersebut.",
    "opsi_d": "Pemerintah berbagai negara belum sepenuhnya menyadari bahaya perubahan iklim.",
    "opsi_e": "Teknologi energi terbarukan dapat menjadi solusi jangka panjang untuk masalah ini.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Kalimat sebelumnya membahas emisi gas rumah kaca dari aktivitas manusia. Kalimat sesudahnya membahas dampaknya. Kalimat C menjadi jembatan logis yang menjelaskan secara spesifik aktivitas manusia penyebab emisi sebelum dampaknya disebutkan.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-154",
    "no_misi_default": 5,
    "tema": "PBM",
    "sub_tema": "Tujuan Penulis",
    "level_kesulitan": 4,
    "materi_pengantar": "Tujuan penulis: informatif (menyampaikan fakta), persuasif (mempengaruhi pembaca), deskriptif (menggambarkan), atau naratif (bercerita). Cermati kata-kata yang mengindikasikan ajakan atau saran.",
    "pertanyaan": "Bacalah teks berikut! Banyak remaja saat ini menghabiskan rata-rata 8 jam per hari di depan layar gadget. Waktu yang seharusnya digunakan untuk belajar dan berolahraga justru tergerus oleh konten digital yang tidak selalu bermanfaat. Penelitian menunjukkan bahwa penggunaan gadget berlebihan berkorelasi dengan meningkatnya risiko depresi, gangguan tidur, dan penurunan prestasi akademik pada remaja. Oleh karena itu, orang tua dan pendidik perlu menerapkan aturan penggunaan gadget yang bijak dan memperkenalkan alternatif kegiatan produktif.\n\nTujuan penulis dalam menyampaikan teks tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Melarang remaja menggunakan gadget sama sekali.",
    "opsi_b": "Menginformasikan dampak negatif penggunaan gadget berlebihan dan mendorong adanya pembatasan yang bijak.",
    "opsi_c": "Mengkritik perkembangan teknologi digital yang semakin pesat.",
    "opsi_d": "Menyarankan orang tua untuk menyita gadget milik anak remaja.",
    "opsi_e": "Melaporkan hasil penelitian tentang pengaruh gadget terhadap kesehatan mental remaja.",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Teks bersifat informatif-persuasif: menginformasikan dampak negatif (data penelitian) sekaligus mendorong tindakan (orang tua dan pendidik perlu menerapkan aturan). Opsi A dan D terlalu ekstrem. Opsi C tidak tepat karena teks tidak mengkritik teknologi. Opsi E terlalu sempit.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-155",
    "no_misi_default": 2,
    "tema": "PK",
    "sub_tema": "Aritmatika",
    "level_kesulitan": 2,
    "materi_pengantar": "Diskon/persen: harga setelah diskon = harga awal × (1 - %diskon). Atau: harga diskon = harga awal × %diskon, lalu kurangi dari harga awal.",
    "pertanyaan": "Sebuah toko memberikan diskon 20% untuk semua produk. Jika harga awal sebuah sepatu adalah Rp450.000,00, maka harga setelah diskon adalah ...",
    "ada_latex": false,
    "opsi_a": "Rp340.000,00",
    "opsi_b": "Rp350.000,00",
    "opsi_c": "Rp360.000,00",
    "opsi_d": "Rp380.000,00",
    "opsi_e": "Rp400.000,00",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Diskon = 20% × Rp450.000,00 = Rp90.000,00. Harga setelah diskon = Rp450.000,00 − Rp90.000,00 = Rp360.000,00. Atau secara langsung: harga = 80% × Rp450.000,00 = Rp360.000,00.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-156",
    "no_misi_default": 3,
    "tema": "PK",
    "sub_tema": "Aljabar",
    "level_kesulitan": 3,
    "materi_pengantar": "Persamaan linear satu variabel: kumpulkan variabel di satu ruas, konstanta di ruas lain. Jika 3x + 7 = 2x + 15, maka 3x − 2x = 15 − 7, sehingga x = 8.",
    "pertanyaan": "Jika 3x + 7 = 2x + 15, maka nilai dari 2x − 5 adalah ...",
    "ada_latex": true,
    "opsi_a": "3",
    "opsi_b": "8",
    "opsi_c": "11",
    "opsi_d": "16",
    "opsi_e": "21",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Dari 3x + 7 = 2x + 15, maka 3x − 2x = 15 − 7, sehingga x = 8. Nilai 2x − 5 = 2(8) − 5 = 16 − 5 = 11.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-157",
    "no_misi_default": 4,
    "tema": "PK",
    "sub_tema": "Geometri",
    "level_kesulitan": 3,
    "materi_pengantar": "Luas persegi panjang = p × l. Luas lingkaran = π × r². Untuk soal gabungan, hitung luas masing-masing bangun lalu operasikan sesuai yang ditanyakan.",
    "pertanyaan": "Sebuah taman berbentuk persegi panjang dengan panjang 15 m dan lebar 8 m. Di dalam taman terdapat kolam berbentuk lingkaran dengan diameter 6 m. Jika π = 3,14, maka luas area taman di luar kolam adalah ...",
    "ada_latex": true,
    "opsi_a": "91,74 m²",
    "opsi_b": "91,26 m²",
    "opsi_c": "92,74 m²",
    "opsi_d": "93,46 m²",
    "opsi_e": "94,00 m²",
    "kunci_jawaban": "A",
    "penjelasan_jawaban": "Luas persegi panjang = 15 × 8 = 120 m². Jari-jari kolam = 6 ÷ 2 = 3 m. Luas kolam = 3,14 × 3² = 3,14 × 9 = 28,26 m². Luas taman di luar kolam = 120 − 28,26 = 91,74 m².",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-158",
    "no_misi_default": 5,
    "tema": "PK",
    "sub_tema": "Statistika",
    "level_kesulitan": 4,
    "materi_pengantar": "Mean = jumlah semua data ÷ banyak data. Median = nilai tengah setelah data diurutkan. Jika data ganjil, median = nilai ke-((n+1)/2). Jika data genap, median = rata-rata dua nilai tengah.",
    "pertanyaan": "Data nilai ulangan matematika 7 siswa adalah: 65, 70, 80, 75, 90, 85, 70. Nilai rata-rata (mean) dan median dari data tersebut berturut-turut adalah ...",
    "ada_latex": false,
    "opsi_a": "Mean = 76,43 dan Median = 75",
    "opsi_b": "Mean = 75 dan Median = 76,43",
    "opsi_c": "Mean = 76,43 dan Median = 70",
    "opsi_d": "Mean = 75 dan Median = 70",
    "opsi_e": "Mean = 70 dan Median = 75",
    "kunci_jawaban": "A",
    "penjelasan_jawaban": "Mean = (65 + 70 + 80 + 75 + 90 + 85 + 70) ÷ 7 = 535 ÷ 7 ≈ 76,43. Setelah diurutkan: 65, 70, 70, 75, 80, 85, 90. Median = nilai ke-4 = 75. Jadi mean ≈ 76,43 dan median = 75.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-159",
    "no_misi_default": 6,
    "tema": "PK",
    "sub_tema": "Aritmatika",
    "level_kesulitan": 4,
    "materi_pengantar": "Soal perbandingan usia: misalkan usia dengan variabel, buat persamaan untuk kondisi sekarang dan kondisi di masa depan/lampau, lalu selesaikan sistem persamaan.",
    "pertanyaan": "Perbandingan usia Ayah dan Anak saat ini adalah 4 : 1. Jika 10 tahun lagi perbandingan usia mereka menjadi 2 : 1, maka usia Ayah saat ini adalah ...",
    "ada_latex": false,
    "opsi_a": "10 tahun",
    "opsi_b": "15 tahun",
    "opsi_c": "20 tahun",
    "opsi_d": "25 tahun",
    "opsi_e": "30 tahun",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Misalkan usia anak = x, maka usia ayah = 4x. Sepuluh tahun lagi: (4x + 10)/(x + 10) = 2/1 → 4x + 10 = 2x + 20 → 2x = 10 → x = 5. Usia ayah = 4 × 5 = 20 tahun.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-160",
    "no_misi_default": 2,
    "tema": "LBI",
    "sub_tema": "Isi Teks",
    "level_kesulitan": 2,
    "materi_pengantar": "Soal fakta tersurat: cari pernyataan yang secara langsung dan eksplisit disebutkan dalam teks. Hindari pernyataan yang hanya bisa disimpulkan atau memerlukan informasi tambahan.",
    "pertanyaan": "Bacalah teks berikut! Indonesia merupakan negara kepulauan terbesar di dunia dengan lebih dari 17.000 pulau yang tersebar dari Sabang hingga Merauke. Kondisi geografis ini menjadikan Indonesia memiliki keragaman budaya yang luar biasa, di mana terdapat lebih dari 300 suku bangsa dan 700 bahasa daerah. Kekayaan budaya ini tercermin dalam berbagai aspek kehidupan, mulai dari adat istiadat, pakaian tradisional, seni pertunjukan, hingga kuliner khas dari masing-masing daerah.\n\nBerdasarkan teks tersebut, pernyataan yang SESUAI adalah ...",
    "ada_latex": false,
    "opsi_a": "Indonesia memiliki sekitar 300 pulau yang tersebar dari Sabang hingga Merauke.",
    "opsi_b": "Keragaman budaya Indonesia disebabkan oleh kondisi geografisnya sebagai negara kepulauan.",
    "opsi_c": "Terdapat sekitar 300 bahasa daerah di Indonesia.",
    "opsi_d": "Seluruh budaya Indonesia berasal dari 300 suku bangsa yang berasal dari satu leluhur.",
    "opsi_e": "Keragaman budaya Indonesia hanya tercermin dalam kuliner dan pakaian tradisional saja.",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Teks secara eksplisit menyebutkan bahwa 'kondisi geografis ini menjadikan Indonesia memiliki keragaman budaya yang luar biasa.' Opsi A salah (17.000 pulau, bukan 300). Opsi C salah (700 bahasa daerah). Opsi D dan E mengandung informasi yang tidak ada dalam teks.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-161",
    "no_misi_default": 3,
    "tema": "LBI",
    "sub_tema": "Ide Pokok",
    "level_kesulitan": 2,
    "materi_pengantar": "Gagasan utama mencakup topik yang dibahas secara menyeluruh dalam paragraf. Untuk paragraf panjang, identifikasi kalimat yang menjadi 'payung' bagi kalimat-kalimat lainnya.",
    "pertanyaan": "Bacalah paragraf berikut! Urbanisasi di Indonesia terus berlangsung dengan pesat seiring berkembangnya kota-kota besar. Setiap tahun, jutaan warga desa pindah ke kota dengan harapan mendapatkan kehidupan yang lebih baik dan lapangan kerja yang lebih beragam. Namun, arus urbanisasi yang tidak terkendali justru menimbulkan berbagai masalah perkotaan seperti kemacetan, permukiman kumuh, dan tekanan terhadap fasilitas publik. Pemerintah perlu merancang kebijakan yang dapat menyeimbangkan pembangunan antara daerah urban dan rural agar migrasi terjadi secara lebih terencana.\n\nGagasan utama paragraf tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Jutaan warga desa pindah ke kota setiap tahunnya.",
    "opsi_b": "Urbanisasi menyebabkan kemacetan dan permukiman kumuh di kota.",
    "opsi_c": "Urbanisasi yang pesat di Indonesia menimbulkan berbagai masalah perkotaan yang perlu diatasi melalui kebijakan yang tepat.",
    "opsi_d": "Pemerintah perlu menghentikan arus urbanisasi dari desa ke kota.",
    "opsi_e": "Pembangunan desa lebih penting daripada pembangunan kota besar.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Paragraf membahas urbanisasi (fenomena), dampak negatifnya (masalah perkotaan), dan solusinya (kebijakan pemerintah). Gagasan utama C mencakup ketiganya secara komprehensif. Opsi lain hanya mencerminkan satu bagian paragraf.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-162",
    "no_misi_default": 4,
    "tema": "LBI",
    "sub_tema": "Pemahaman Bacaan",
    "level_kesulitan": 3,
    "materi_pengantar": "Makna tersirat: informasi yang tidak disebutkan secara langsung tetapi dapat dipahami dari keseluruhan teks. Berbeda dengan simpulan tersurat yang langsung ada di teks.",
    "pertanyaan": "Bacalah teks berikut! Sebuah survei menunjukkan bahwa 78% pekerja yang bekerja dari rumah (WFH) mengaku produktivitas mereka meningkat dibandingkan saat bekerja di kantor. Mereka menyebutkan berkurangnya waktu perjalanan dan lingkungan kerja yang nyaman sebagai faktor utama. Namun, 65% dari responden yang sama juga mengaku kesulitan memisahkan urusan pekerjaan dan urusan pribadi. Selain itu, 42% merasa kesepian karena kurangnya interaksi sosial dengan rekan kerja.\n\nMakna tersirat yang paling tepat dari teks tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Bekerja dari rumah (WFH) sepenuhnya lebih baik daripada bekerja di kantor.",
    "opsi_b": "WFH memiliki keuntungan dalam hal produktivitas, tetapi juga membawa tantangan pada keseimbangan kehidupan dan interaksi sosial.",
    "opsi_c": "Seluruh pekerja sebaiknya beralih ke sistem WFH penuh waktu.",
    "opsi_d": "Perusahaan harus memaksa karyawan kembali bekerja di kantor karena WFH tidak efektif.",
    "opsi_e": "Survei tentang WFH tidak dapat diandalkan karena data yang diambil terlalu subjektif.",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Teks tidak secara eksplisit menyatakan WFH baik atau buruk, melainkan menyajikan keduanya: kelebihan (produktivitas meningkat 78%) dan kelemahan (65% kesulitan work-life balance, 42% kesepian). Makna tersirat B paling seimbang dan tepat.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-163",
    "no_misi_default": 5,
    "tema": "LBI",
    "sub_tema": "Tujuan Penulis",
    "level_kesulitan": 4,
    "materi_pengantar": "Tujuan penulis ditentukan dari keseluruhan isi dan nada teks: apakah memuat fakta saja (informatif), ajakan (persuasif), kritik (argumentatif), atau gabungan. Perhatikan kata-kata yang mengindikasikan saran/rekomendasi.",
    "pertanyaan": "Bacalah teks berikut! Generasi milenial dan Gen Z dikenal sebagai generasi yang akrab dengan teknologi digital. Namun, survei menunjukkan bahwa kemampuan literasi finansial mereka sangat rendah. Banyak di antara mereka tidak memiliki tabungan, terjebak dalam utang konsumtif, dan tidak memahami cara berinvestasi. Padahal, pemahaman tentang keuangan pribadi sangat krusial untuk membangun masa depan yang stabil. Lembaga pendidikan perlu memasukkan materi literasi finansial dalam kurikulum mereka sejak dini agar generasi mendatang lebih siap secara finansial.\n\nTujuan penulis dalam teks tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "Mengkritik generasi milenial dan Gen Z yang dinilai boros dan tidak bertanggung jawab.",
    "opsi_b": "Memuji kemampuan teknologi digital yang dikuasai generasi muda Indonesia.",
    "opsi_c": "Menginformasikan rendahnya literasi finansial generasi muda sekaligus mendorong penambahan materi literasi finansial dalam kurikulum pendidikan.",
    "opsi_d": "Menjelaskan cara berinvestasi yang tepat bagi generasi muda.",
    "opsi_e": "Melaporkan hasil survei tentang kebiasaan menabung generasi milenial dan Gen Z.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Teks bersifat informatif-persuasif: mengidentifikasi masalah (literasi finansial rendah) didukung data, lalu memberikan rekomendasi solusi (kurikulum literasi finansial). Opsi E terlalu sempit. Opsi A bersifat negatif yang tidak sesuai nada teks.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-164",
    "no_misi_default": 6,
    "tema": "LBI",
    "sub_tema": "Fakta dalam Teks",
    "level_kesulitan": 4,
    "materi_pengantar": "Fakta: pernyataan yang dapat dibuktikan kebenarannya, biasanya berupa data, angka, hasil penelitian, atau peristiwa nyata. Opini: penilaian subjektif. Hindari pernyataan yang memperluas atau mengubah fakta dari teks.",
    "pertanyaan": "Bacalah teks berikut! Madu telah digunakan sebagai obat alami sejak ribuan tahun lalu. Kandungan hidrogen peroksida dalam madu terbukti secara ilmiah memiliki sifat antibakteri. Sebuah penelitian dalam jurnal Asian Pacific Journal of Tropical Medicine menemukan bahwa madu mampu menghambat pertumbuhan bakteri Staphylococcus aureus hingga 95%. Selain itu, madu mengandung antioksidan flavonoid yang dapat membantu melindungi sel dari kerusakan radikal bebas. Meskipun demikian, bayi di bawah usia satu tahun tidak boleh mengonsumsi madu karena risiko botulisme.\n\nManakah yang merupakan FAKTA dalam teks tersebut?",
    "ada_latex": false,
    "opsi_a": "Madu adalah obat terbaik di dunia yang tidak memiliki efek samping apa pun.",
    "opsi_b": "Madu mengandung hidrogen peroksida yang terbukti secara ilmiah bersifat antibakteri.",
    "opsi_c": "Seluruh jenis bakteri dapat dihambat pertumbuhannya oleh madu.",
    "opsi_d": "Semua bayi di bawah dua tahun harus menghindari konsumsi madu.",
    "opsi_e": "Antioksidan dalam madu dapat menyembuhkan semua penyakit akibat radikal bebas.",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Pernyataan B langsung sesuai dengan teks ('terbukti secara ilmiah'). Opsi A salah (teks tidak menyebut madu bebas efek samping). Opsi C berlebihan (hanya Staphylococcus aureus). Opsi D salah (teks menyebut di bawah satu tahun). Opsi E berlebihan (teks tidak menyebut 'semua penyakit').",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-165",
    "no_misi_default": 2,
    "tema": "LBIng",
    "sub_tema": "Reading Comprehension",
    "level_kesulitan": 2,
    "materi_pengantar": "Main idea: the central point of a passage. It covers the whole passage, not just one detail. Look for the sentence that all other sentences support or elaborate on.",
    "pertanyaan": "Read the following passage! The global demand for electric vehicles (EVs) has surged dramatically in recent years. In 2023, EV sales accounted for 18% of total car sales worldwide, a significant increase from just 4% in 2020. This rapid growth is driven by falling battery costs, government incentives, and growing environmental awareness among consumers. Major automakers are now committing billions of dollars to transition their production lines to electric models.\n\nWhat is the main idea of the passage?",
    "ada_latex": false,
    "opsi_a": "The environmental impact of traditional gasoline vehicles.",
    "opsi_b": "Government policies supporting electric vehicle adoption.",
    "opsi_c": "The rapid growth of electric vehicle sales and its driving factors.",
    "opsi_d": "The challenges faced by automakers in transitioning to electric models.",
    "opsi_e": "Battery technology improvements in the electric vehicle industry.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "The passage discusses the surge in EV demand (from 4% to 18%) and explains why it happened (falling costs, government incentives, environmental awareness). Option C captures both elements. Other options only cover specific details mentioned in the passage.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-166",
    "no_misi_default": 3,
    "tema": "LBIng",
    "sub_tema": "Literasi Inggris",
    "level_kesulitan": 3,
    "materi_pengantar": "Factual questions: find information explicitly stated in the passage. Avoid answers that contradict or go beyond what the text says. Key strategy: locate the relevant sentence, then match with the answer choice.",
    "pertanyaan": "Read the following passage! Artificial intelligence (AI) is increasingly being integrated into healthcare systems around the world. AI-powered tools can analyze medical images such as X-rays and MRI scans with remarkable accuracy, often outperforming human radiologists in detecting certain conditions. A study published in Nature Medicine found that an AI system correctly identified malignant tumors in breast cancer screenings 94.5% of the time, compared to 88% accuracy for human doctors. However, experts caution that AI should be used as a tool to assist doctors, not to replace them, as human judgment remains essential in complex medical decision-making.\n\nBased on the passage, which statement is TRUE?",
    "ada_latex": false,
    "opsi_a": "AI has already completely replaced radiologists in most hospitals worldwide.",
    "opsi_b": "Human doctors achieved a 94.5% accuracy rate in detecting breast cancer.",
    "opsi_c": "The AI system mentioned in the passage outperformed human doctors in breast cancer detection accuracy.",
    "opsi_d": "Experts believe AI will eventually replace all human medical professionals.",
    "opsi_e": "AI tools can only analyze MRI scans, not X-rays or other medical images.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "The passage states the AI system had 94.5% accuracy while human doctors had 88% — meaning AI outperformed humans in this specific task. Option A contradicts the expert caution. Option B reverses the numbers. Option D is not stated. Option E is the opposite of what the text says.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-167",
    "no_misi_default": 4,
    "tema": "LBIng",
    "sub_tema": "Vocabulary",
    "level_kesulitan": 3,
    "materi_pengantar": "Vocabulary in context: determine word meaning from surrounding sentences, not dictionary definitions alone. Look for clues: synonyms nearby, contrast words (but/however), or explanatory phrases.",
    "pertanyaan": "Read the following passage! The Amazon rainforest, often called 'the lungs of the Earth,' plays a pivotal role in regulating the global climate. It absorbs billions of tons of carbon dioxide annually and releases oxygen, making it indispensable to maintaining the Earth's atmospheric balance. However, rampant deforestation driven by agricultural expansion, illegal logging, and mining activities threatens to transform this ecosystem into a savanna-like landscape within decades.\n\nThe word 'indispensable' in the passage is closest in meaning to ...",
    "ada_latex": false,
    "opsi_a": "Replaceable and flexible",
    "opsi_b": "Beneficial but optional",
    "opsi_c": "Absolutely essential and irreplaceable",
    "opsi_d": "Environmentally friendly",
    "opsi_e": "Difficult to measure or quantify",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "'Indispensable' means absolutely necessary — something that cannot be done without. The context shows the Amazon is described as essential to the Earth's atmospheric balance due to its oxygen production, implying it cannot be replaced. Option A is the opposite. Options B, D, and E do not match the meaning.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-168",
    "no_misi_default": 5,
    "tema": "LBIng",
    "sub_tema": "Literasi Inggris",
    "level_kesulitan": 4,
    "materi_pengantar": "Author's purpose: WHY the author wrote the passage. Categories: to inform (factual), to persuade (advocate), to describe, or to entertain. Look for recommendations, warnings, or calls to action as clues to persuasive intent.",
    "pertanyaan": "Read the following passage! Despite being home to some of the world's most talented young scientists, many developing countries continue to experience a significant 'brain drain' — the emigration of educated professionals to wealthier nations. Surveys indicate that 70% of science graduates from sub-Saharan Africa seek employment abroad due to limited research funding, poor infrastructure, and political instability. This phenomenon not only deprives developing nations of their intellectual capital but also widens the technological gap between wealthy and poor countries. International cooperation and investment in local research institutions are urgently needed to reverse this trend.\n\nThe primary purpose of the passage is to ...",
    "ada_latex": false,
    "opsi_a": "Celebrate the professional achievements of scientists from developing countries.",
    "opsi_b": "Describe the living and working conditions in sub-Saharan African countries.",
    "opsi_c": "Highlight the problem of brain drain in developing countries and advocate for international solutions.",
    "opsi_d": "Criticize wealthy countries for deliberately attracting scientists from poorer nations.",
    "opsi_e": "Explain the personal motivations of scientists who choose to work abroad.",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "The passage identifies the problem (brain drain, 70% of graduates leave), explains its causes and consequences, then calls for action ('urgently needed'). This combines informative and persuasive purposes. Option D is too extreme; Option B is too narrow; Options A and E are not the passage's focus.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-169",
    "no_misi_default": 6,
    "tema": "LBIng",
    "sub_tema": "Literasi Inggris",
    "level_kesulitan": 4,
    "materi_pengantar": "Conditional sentences: Type 1 (real/possible): if + Simple Present, will + Verb. Type 2 (unreal/hypothetical): if + Simple Past, would + Verb. Passive voice in conditionals: if + subject + is/are + past participle.",
    "pertanyaan": "Choose the correct form of the verb to complete the sentence below!\n\nClimate scientists have long warned that if greenhouse gas emissions _____ drastically by 2030, the average global temperature will likely exceed 1.5°C above pre-industrial levels, triggering irreversible environmental consequences.",
    "ada_latex": false,
    "opsi_a": "are not reduced",
    "opsi_b": "will not be reduced",
    "opsi_c": "not reduced",
    "opsi_d": "were not reducing",
    "opsi_e": "have not been reduced",
    "kunci_jawaban": "A",
    "penjelasan_jawaban": "This is a Type 1 Conditional (real possibility): 'if + Simple Present, will + Verb.' The if-clause requires the Simple Present tense in passive voice (since emissions are reduced by people): 'are not reduced.' Option B (will) is wrong for if-clauses. Option D uses Simple Past (Type 2). Option E uses Present Perfect.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-170",
    "no_misi_default": 2,
    "tema": "PM",
    "sub_tema": "Statistika",
    "level_kesulitan": 2,
    "materi_pengantar": "Rata-rata (mean): total nilai dibagi banyak data. Jika rata-rata diketahui, total = rata-rata × banyak data. Saat data baru ditambahkan: total baru = total lama + nilai baru, lalu dibagi jumlah data baru.",
    "pertanyaan": "Nilai rata-rata ulangan 5 siswa adalah 75. Jika satu siswa lagi mengikuti ujian susulan dan mendapat nilai 90, maka nilai rata-rata dari 6 siswa tersebut adalah ...",
    "ada_latex": false,
    "opsi_a": "76,5",
    "opsi_b": "77",
    "opsi_c": "77,5",
    "opsi_d": "78",
    "opsi_e": "78,5",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Total nilai 5 siswa = 5 × 75 = 375. Dengan tambahan nilai 90, total menjadi 375 + 90 = 465. Rata-rata 6 siswa = 465 ÷ 6 = 77,5.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-171",
    "no_misi_default": 3,
    "tema": "PM",
    "sub_tema": "Aljabar",
    "level_kesulitan": 3,
    "materi_pengantar": "Sistem persamaan linear dua variabel (SPLDV): gunakan metode eliminasi atau substitusi. Eliminasi: kalikan salah satu atau kedua persamaan agar salah satu koefisien variabel sama, lalu kurangkan.",
    "pertanyaan": "Harga 3 buku dan 2 pensil adalah Rp28.000,00. Harga 2 buku dan 5 pensil adalah Rp26.000,00. Harga satu buku adalah ...",
    "ada_latex": false,
    "opsi_a": "Rp6.000,00",
    "opsi_b": "Rp6.500,00",
    "opsi_c": "Rp7.000,00",
    "opsi_d": "Rp8.000,00",
    "opsi_e": "Rp9.000,00",
    "kunci_jawaban": "D",
    "penjelasan_jawaban": "Misalkan harga buku = b dan pensil = p. Persamaan: 3b + 2p = 28.000 ...(1) dan 2b + 5p = 26.000 ...(2). Kalikan (1)×5 dan (2)×2: 15b + 10p = 140.000 dan 4b + 10p = 52.000. Kurangkan: 11b = 88.000, sehingga b = Rp8.000,00.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-172",
    "no_misi_default": 4,
    "tema": "PM",
    "sub_tema": "Geometri",
    "level_kesulitan": 3,
    "materi_pengantar": "Volume kubus = s³. Susunan benda dalam wadah: bagi panjang sisi wadah dengan diameter/ukuran benda untuk tiap dimensi, lalu kalikan ketiganya untuk mendapat total.",
    "pertanyaan": "Sebuah kotak berbentuk kubus dengan panjang rusuk 12 cm akan diisi bola-bola kecil yang masing-masing berdiameter 4 cm. Jika bola disusun dalam barisan teratur (tidak bertumpuk sembarangan), banyak bola yang dapat dimasukkan ke dalam kotak adalah ...",
    "ada_latex": false,
    "opsi_a": "8 bola",
    "opsi_b": "16 bola",
    "opsi_c": "27 bola",
    "opsi_d": "64 bola",
    "opsi_e": "125 bola",
    "kunci_jawaban": "C",
    "penjelasan_jawaban": "Setiap sisi rusuk kubus (12 cm) dapat memuat 12 ÷ 4 = 3 bola. Dalam susunan teratur tiga dimensi: total bola = 3 × 3 × 3 = 27 bola.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-173",
    "no_misi_default": 5,
    "tema": "PM",
    "sub_tema": "Statistika",
    "level_kesulitan": 4,
    "materi_pengantar": "Peluang tanpa pengembalian: P(A∩B) = (banyak cara memilih A) / (banyak cara memilih total). Gunakan kombinasi C(n,r) = n! / (r!(n-r)!) untuk memilih tanpa memperhatikan urutan.",
    "pertanyaan": "Sebuah kantong berisi 5 kelereng merah dan 3 kelereng biru. Jika dua kelereng diambil secara acak tanpa pengembalian, peluang kedua kelereng yang terambil berwarna merah adalah ...",
    "ada_latex": true,
    "opsi_a": "5/28",
    "opsi_b": "5/14",
    "opsi_c": "10/28",
    "opsi_d": "25/64",
    "opsi_e": "3/28",
    "kunci_jawaban": "B",
    "penjelasan_jawaban": "Banyak cara memilih 2 kelereng merah dari 5: C(5,2) = 10. Banyak cara memilih 2 kelereng dari 8: C(8,2) = 28. Peluang = 10/28 = 5/14.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  },
  {
    "id": "S-174",
    "no_misi_default": 6,
    "tema": "PM",
    "sub_tema": "Kombinatorika",
    "level_kesulitan": 5,
    "materi_pengantar": "Permutasi P(n,r) = n!/(n-r)!: digunakan saat urutan/posisi berpengaruh (misal: jabatan berbeda). Kombinasi C(n,r) = n!/(r!(n-r)!): digunakan saat urutan tidak berpengaruh (misal: memilih anggota tim).",
    "pertanyaan": "Dari 8 orang kandidat, akan dipilih 3 orang untuk mengisi jabatan Ketua, Sekretaris, dan Bendahara. Banyaknya cara pemilihan yang mungkin adalah ...",
    "ada_latex": true,
    "opsi_a": "56",
    "opsi_b": "112",
    "opsi_c": "168",
    "opsi_d": "336",
    "opsi_e": "504",
    "kunci_jawaban": "D",
    "penjelasan_jawaban": "Karena setiap jabatan berbeda (Ketua ≠ Sekretaris ≠ Bendahara), maka urutan berpengaruh → gunakan permutasi. P(8,3) = 8!/(8-3)! = 8 × 7 × 6 = 336 cara.",
    "sudah_dipakai_misi": [],
    "status": "AKTIF",
    "dibuat_tanggal": "2026-04-23",
    "sumber": "Soal Baru UTBK 2026"
  }
];